### ISSUE TITLE
MSAL causes crash if a WKWebView() variable is present

### ISSUE THREAD

**Issue by matt-matt1** [Azure-Samples/ms-identity-mobile-apple-swift-objc#71] opened 2020-09-18 17:03 UTC
I am programming in _Xcode 10_ with _Swift 4.2_ on _macOS 10.13.6_ using _MSAL 1.0.5_.  I believe this is a _bug_.
In my app theres a procedure to add a **onedrive** connection - that works fine - it then makes another button to explore the drive.
When the user clicks this (the second) button, usually the drives are listed, and the user can enter in sub-directories, etc.
However the app would instead crash and Xcode would throw a bizarre error.  (It takes about a second before this.)
I couldn't find the source of this crash.
(Everything was working a few days ago, so I recalled what I changed..)  When I removed the line '_var web = WKWebView()_' (in the same class), it (my explore method, etc.) worked again.  (Again when this variable was added = crash; removed = no crash.  Over and over again.)
So there seem some clash with 'var web = WKWebView()' variable or the WKWebView itself.

**Comment by NerevarineRule** [comment] 2020-09-22 22:35
@matt-matt1  Could you please provide more details on what the error was and provide crash log files if you have any.
Could you also retry with the latest MSAL library - 1.1.10

**Comment by matt-matt1** [comment] 2020-09-23 16:30
Hi

Sorry this computer won’t upgrade any further and therefore Xcode is maxxed at version 10.1 and therefore can other handle up to Swift 4.2 and therefore cannot use a higher version of MSAL.

The crash happens after I click drives (to obtain the root contents) that fetches from drives/<id>/root/children.  It prints the item ids (ie. successful fetch), as per the code I applied, then the crash.

I cannot find the crash point by stepping about the location…  However the next step is that it waits for the user to click a file of folder.  A breakpoint confirm that this method is not called before/during the crash.

(When I glance at the UI, no contents are displayed.)



Please find the editor window screenshot attached.  Xcode comes to the front and highlight an assembly language line, and I cannot understand anything on this screen.

How can I get the log(s) for you?

After a careful look it seems the fetch is working OK, so it may not be MSAL at fault.  But other aspects of the app seems to work as expected - without crash.  Only after the MSGraph call…  My method forms the URL based on the file/folder path, calls it and decodes the returned JSON (inside a do..catch block) and puts the entries (and display their IDs) into my collectionView (and refreshes it).

**Comment by NerevarineRule** [comment] 2020-10-03 22:24
Sorry for the delay. If you would like to enable logging - please refer to here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc

**Comment by matt-matt1** [comment] 2020-10-09 16:08
Hi

UPDATE
It won’t crash now…
First I added into AppDelegate:

		MSALGlobalConfig.loggerConfig.setLogCallback { (logLevel, message, containsPII) in
			if let displayableMessage = message {
				if (!containsPII) {
					#if DEBUG
					// NB! This sample uses print just for testing purposes
					// You should only ever log to NSLog in debug mode to prevent leaking potentially sensitive information
					print(displayableMessage)
					#endif
				}
			}
		}

That require to also import the MSAL library, that I only used in another class before…
After that it won’t crash as before, when tested.
Then I again tested with the code (and import MSAL) comment-out.  No crash.
All I can attribute it to is maybe something invalid was held in the app cache.  I recall doing a few cleans of the project directory and rebuilds.
FYI my log is below.
----
Normal log:
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Init MSIDMacACLPersistentTokenCache
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Using "Masked(not-null)" Team ID.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Init MSIDMacKeychainTokenCache with keychainGroup: Microsoft Credentials.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Querying MSAL account for identifier c162b47e
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Trying to find keychain items...
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Keychain find status: 0.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] (Default accessor) Get accounts.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Trying to find keychain items...
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Keychain find status: 0.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Trying to find keychain items...
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Keychain find status: 0.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] (Default accessor) Looking for token with aliases (null), tenant (null), clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes (null)
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] (Default accessor) Found 1 tokens
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] (Default accessor) Found the following accounts in default accessor: MaskedArray(count=1)
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] (Default accessor) Found the following accounts in other accessors: MaskedArray(count=1)
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Returning account for parameters with environment login.windows.net, identifier c162b47e, username auth.placeholder-e04eb290@yumatechnical.com
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Found MSAL account with identifier c162b47e, username auth.placeholder-e04eb290@yumatechnical.com
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25] Request authority cache look up for https://login.microsoftonline.com/common, using https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad instead
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] -[MSALPublicClientApplication acquireTokenSilentForScopes:(
    "user.read",
    "Files.ReadWrite.All"
)
                                                  account:Masked(not-null)
                                                authority:(null)
                                        validateAuthority:Yes
                                             forceRefresh:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Beginning silent flow.
TID=229428 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Resolving authority: Masked(not-null), upn: auth.placeholder-e04eb290@yumatechnical.com
TID=229583 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] No cached preferred_network for authority
TID=229583 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:25 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Waiting on Authority Validation Queue
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Caching AAD Environements
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Resolved authority, validated: YES, error: 0
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Looking for access token...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant 9188040d-6c67-4c5b-b112-36a304b66dad, clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes user.read Files.ReadWrite.All
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default accessor) Found 1 tokens
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Found access token for account c162b47e:auth.placeholder-e04eb290@yumatechnical.com which expires in -147775.726172
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Access token has expired, removing it...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default cache) Removing credential Masked(not-null) for userID Masked(not-null) with environment login.windows.net, realm 9188040d-6c67-4c5b-b112-36a304b66dad, clientID 164b3137-9787-44b1-8161-c09e9f7e2c56,
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Looking for Family Refresh token...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Family Refresh token wasn't found, looking for Refresh token...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant (null), clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes (null)
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default accessor) Found 1 tokens
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Found Refresh token, using it...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Refreshing access token
TID=229583 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Returned from Authority Validation Queue
TID=230064 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:27 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Acquiring Access token via Refresh token...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Validate and save token response...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default accessor) Saving multi resource refresh token
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] (Default cache) Removing credentials with type AccessToken, environment login.windows.net, realm 9188040d-6c67-4c5b-b112-36a304b66dad, clientID 164b3137-9787-44b1-8161-c09e9f7e2c56, unique user ID Masked(not-null), target User.Read Files.ReadWrite.All openid profile
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Trying to find keychain items...
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28] Keychain find status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item, item info Masked(not-null).
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Saving keychain item
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Keychain update status: 0.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Returning token result.
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] Silent flow finished result (not-null), error: 0 error domain: (null)
TID=229954 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:27:28 - 7E432533-1038-4613-A0F6-9B195A838FB8] [MSAL] acquireTokenSilent returning with at: 82b9239 scopes:(
    "User.Read",
    "Files.ReadWrite.All",
    openid,
    profile
) expiration:2020-10-09 16:27:28 +0000


Log with "var window: NSWindow!”:
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Init MSIDMacACLPersistentTokenCache
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Using "Masked(not-null)" Team ID.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Init MSIDMacKeychainTokenCache with keychainGroup: Microsoft Credentials.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Querying MSAL account for identifier c162b47e
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Trying to find keychain items...
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Keychain find status: 0.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] (Default accessor) Get accounts.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Trying to find keychain items...
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Keychain find status: 0.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Trying to find keychain items...
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Keychain find status: 0.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] (Default accessor) Looking for token with aliases (null), tenant (null), clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes (null)
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] (Default accessor) Found 1 tokens
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] (Default accessor) Found the following accounts in default accessor: MaskedArray(count=1)
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] (Default accessor) Found the following accounts in other accessors: MaskedArray(count=1)
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Returning account for parameters with environment login.windows.net, identifier c162b47e, username auth.placeholder-e04eb290@yumatechnical.com
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Found MSAL account with identifier c162b47e, username auth.placeholder-e04eb290@yumatechnical.com
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Request authority cache look up for https://login.microsoftonline.com/common, using https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad instead
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] -[MSALPublicClientApplication acquireTokenSilentForScopes:(
    "user.read",
    "Files.ReadWrite.All"
)
                                                  account:Masked(not-null)
                                                authority:(null)
                                        validateAuthority:Yes
                                             forceRefresh:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Beginning silent flow.
TID=237107 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Resolving authority: Masked(not-null), upn: auth.placeholder-e04eb290@yumatechnical.com
TID=237209 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] No cached preferred_network for authority
TID=237209 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Waiting on Authority Validation Queue
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Caching AAD Environements
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] networkHost: login.microsoftonline.com, cacheHost: login.windows.net, aliases: login.microsoftonline.com, login.windows.net, login.microsoft.com, sts.windows.net
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] networkHost: login.partner.microsoftonline.cn, cacheHost: login.partner.microsoftonline.cn, aliases: login.partner.microsoftonline.cn, login.chinacloudapi.cn
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] networkHost: login.microsoftonline.de, cacheHost: login.microsoftonline.de, aliases: login.microsoftonline.de
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] networkHost: login.microsoftonline.us, cacheHost: login.microsoftonline.us, aliases: login.microsoftonline.us, login.usgovcloudapi.net
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] networkHost: login-us.microsoftonline.com, cacheHost: login-us.microsoftonline.com, aliases: login-us.microsoftonline.com
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Resolved authority, validated: YES, error: 0
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Looking for access token...
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant 9188040d-6c67-4c5b-b112-36a304b66dad, clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes user.read Files.ReadWrite.All
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Found 1 tokens
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Found access token for account c162b47e:auth.placeholder-e04eb290@yumatechnical.com which expires in 3355.097813
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Found valid access token.
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Looking for family refresh token...
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Didn't find family refresh token with error: Masked(null)
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Looking for app refresh token...
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant (null), clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes (null)
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Trying to find keychain items...
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Keychain find status: 0.
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Found 1 tokens
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Found app refresh token.
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Looking for token with aliases (
    "login.windows.net",
    "login.microsoftonline.com",
    "login.windows.net",
    "login.microsoft.com",
    "sts.windows.net"
), tenant 9188040d-6c67-4c5b-b112-36a304b66dad, clientId 164b3137-9787-44b1-8161-c09e9f7e2c56, scopes (null)
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] (Default accessor) Found 1 tokens
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Found id token Masked(not-null) for account c162b47e:auth.placeholder-e04eb290@yumatechnical.com.
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Trying to find keychain items...
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32] Keychain find status: 0.
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Silent flow finished result (not-null), error: 0 error domain: (null)
TID=237208 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] acquireTokenSilent returning with at: 82b9239 scopes:(
    "User.Read",
    "Files.ReadWrite.All",
    openid,
    profile
) expiration:2020-10-09 16:27:28 +0000
TID=237209 MSAL 1.0.5 Mac 10.13.6 [2020-10-09 15:31:32 - FD48EF63-C97E-4F9D-A997-0D85BC5F9C56] [MSAL] Returned from Authority Validation Queue

**Comment by NerevarineRule** [comment] 2020-10-11 22:07
Thanks for providing the log, and glad to hear that the issue has been resolved. I will close the issue since the issue is now gone.

**Closed by NerevarineRule** 2020-10-11 22:08 UTC
Labels: question
