### ISSUE TITLE
Use another account

### ISSUE THREAD

**Issue by GithubAshishHere** [Azure-Samples/ms-identity-mobile-apple-swift-objc#62] opened 2020-02-13 10:14 UTC
Not working: Login successfully with one user and then without killing the application and again try to login "Use another account". It will ask for the new email to enter. After entering a new email and click on next. it's automatically getting old signed in account and login with that old account successfully.

Working: if I login successfully with one account and kill application then again open the application and go to the option "Use another account". Enter a new email address now it's asking for the password and login with new enter email.

In short why I need to kill application to log in with Use another account.
How can I login with another account without kill the application?
Waiting for the response. Thank you.

**Comment by oldalton** [comment] 2020-03-19 17:58
Closing as duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/850

**Closed by oldalton** 2020-03-19 17:58 UTC
Labels: question
